### PR TITLE
fix: reload chan details after funding (fixes #29)

### LINKED ISSUE #29: Reload paychan amount after funding
The plugin should reload the channel amount after it submitted a funding tx.

### PR DESCRIPTION
**Pull request by dappelt**
fixes #29

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -562,6 +562,7 @@ class Plugin extends MiniAccountsPlugin {
         amount: OUTGOING_CHANNEL_DEFAULT_AMOUNT
       })
         .then(async () => {
+          account.setClientChannel(clientChannel) // reloads the channel amount
```
Comment (sharafian) [inline index.js]: This is an async call; shouldn't it be `await`ed here?

Comment (dappelt) [reply index.js]: Fixed
